#!/usr/bin/env python3
"""Golden-vector tests for the hmac-secret extension (CTAP2 6.6, classic).

The driver cannot run on the host, so correctness is pinned three ways:

1. `tests/hmac_vectors.json` holds vectors generated by `gen_hmac_vectors.py`;
   the reference algorithm (SHA-256(ECDH x), AES-256-CBC, HMAC-SHA-256 — the
   exact scheme fido2 0.8.1's client implements and Windows Hello expects) is
   recomputed here independently and must match the file.
2. The same vectors are embedded as C arrays in the driver's `hmac_selftest`
   sysfs node; the arrays must byte-match the JSON.
3. Source shape checks pin the crypto primitives and the CTAP error that tells
   Windows a credential has no secret.

The on-device check is `cat /sys/kernel/abk_fido_key/hmac_selftest`.
"""

from __future__ import annotations

import hashlib
import hmac
import json
import re
import unittest
from pathlib import Path

try:
    from cryptography.hazmat.primitives import hashes
    from cryptography.hazmat.primitives.asymmetric import ec
    from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes

    CRYPTOGRAPHY = True
except ImportError:  # pragma: no cover - CI installs cryptography
    CRYPTOGRAPHY = False

REPOSITORY = Path(__file__).resolve().parents[1]
DRIVER = REPOSITORY / "files/drivers/abk_fido_key/core.c"
VECTORS = Path(__file__).with_name("hmac_vectors.json")


def _aes_cbc_enc(key: bytes, plain: bytes) -> bytes:
    enc = Cipher(algorithms.AES(key), modes.CBC(b"\x00" * 16)).encryptor()
    return enc.update(plain) + enc.finalize()


def _reference(
    cred_priv_hex: str, platform_pub_hex: str, cred_secret_hex: str,
    salt1_hex: str, salt2_hex: str,
) -> dict[str, str]:
    cred_priv = int.from_bytes(bytes.fromhex(cred_priv_hex), "big")
    platform_pub = bytes.fromhex(platform_pub_hex)
    cred_secret = bytes.fromhex(cred_secret_hex)
    salt1 = bytes.fromhex(salt1_hex)
    salt2 = bytes.fromhex(salt2_hex)

    x = int.from_bytes(platform_pub[:32], "big")
    y = int.from_bytes(platform_pub[32:], "big")
    cred_pub = ec.EllipticCurvePublicNumbers(x, y, ec.SECP256R1()).public_key()
    shared_x = ec.derive_private_key(cred_priv, ec.SECP256R1()).exchange(
        ec.ECDH(), cred_pub
    )
    z = hashlib.sha256(shared_x).digest()

    salt_enc = _aes_cbc_enc(z, salt1 + salt2)
    salt_auth = hmac.new(z, salt_enc, hashlib.sha256).digest()[:16]
    output1 = hmac.new(cred_secret, salt1, hashlib.sha256).digest()
    output2 = hmac.new(cred_secret, salt2, hashlib.sha256).digest()
    output_enc = _aes_cbc_enc(z, output1 + output2)
    return {
        "z": z.hex(),
        "salt_enc": salt_enc.hex(),
        "salt_auth": salt_auth.hex(),
        "output1": output1.hex(),
        "output2": output2.hex(),
        "output_enc": output_enc.hex(),
    }


_C_ARRAY = re.compile(
    r"static const u8 (\w+)\[\d+\] = \{(.*?)\};", flags=re.DOTALL
)


def _c_arrays(text: str) -> dict[str, bytes]:
    arrays: dict[str, bytes] = {}
    for match in _C_ARRAY.finditer(text):
        name = match.group(1)
        body = match.group(2)
        hexes = [int(h, 16) for h in re.findall(r"0x([0-9a-fA-F]{2})", body)]
        arrays[name] = bytes(hexes)
    return arrays


@unittest.skipUnless(
    CRYPTOGRAPHY, "cryptography not installed (CI installs it)"
)
class GoldenVectorTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.vectors = json.loads(VECTORS.read_text())

    def test_reference_recomputation_matches_json(self) -> None:
        got = _reference(
            self.vectors["cred_priv"],
            self.vectors["platform_pub"],
            self.vectors["cred_secret"],
            self.vectors["salt1"],
            self.vectors["salt2"],
        )
        for field in ("z", "salt_enc", "salt_auth", "output1", "output2",
                      "output_enc"):
            self.assertEqual(self.vectors[field], got[field], field)

    def test_reference_decrypt_round_trips(self) -> None:
        z = bytes.fromhex(self.vectors["z"])
        self.assertEqual(
            bytes.fromhex(self.vectors["salt1"]) + bytes.fromhex(self.vectors["salt2"]),
            self._cbc_dec(z, bytes.fromhex(self.vectors["salt_enc"])),
        )
        self.assertEqual(
            bytes.fromhex(self.vectors["output1"]) + bytes.fromhex(self.vectors["output2"]),
            self._cbc_dec(z, bytes.fromhex(self.vectors["output_enc"])),
        )

    @staticmethod
    def _cbc_dec(key: bytes, ciphertext: bytes) -> bytes:
        dec = Cipher(algorithms.AES(key), modes.CBC(b"\x00" * 16)).decryptor()
        return dec.update(ciphertext) + dec.finalize()


class DriverShapeTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.driver = DRIVER.read_text()
        cls.vectors = json.loads(VECTORS.read_text())

    def test_embedded_selftest_arrays_match_json(self) -> None:
        arrays = _c_arrays(self.driver)
        self.assertEqual(
            bytes.fromhex(self.vectors["cred_priv"]),
            arrays.get("abk_fido_selftest_cred_priv"),
        )
        self.assertEqual(
            bytes.fromhex(self.vectors["platform_pub"]),
            arrays.get("abk_fido_selftest_platform_xy"),
        )
        self.assertEqual(
            bytes.fromhex(self.vectors["cred_secret"]),
            arrays.get("abk_fido_selftest_cred_secret"),
        )
        self.assertEqual(
            bytes.fromhex(self.vectors["salt_enc"]),
            arrays.get("abk_fido_selftest_salt_enc"),
        )
        self.assertEqual(
            bytes.fromhex(self.vectors["salt_auth"]),
            arrays.get("abk_fido_selftest_salt_auth"),
        )
        self.assertEqual(
            bytes.fromhex(self.vectors["z"]),
            arrays.get("abk_fido_selftest_want_z"),
        )
        self.assertEqual(
            bytes.fromhex(self.vectors["output_enc"]),
            arrays.get("abk_fido_selftest_want_output_enc"),
        )

    def _assert_text(self, needle: str, message: str) -> None:
        self.assertIn(needle, self.driver, message)

    def test_crypto_primitives_match_the_classic_extension(self) -> None:
        # AES-256-CBC + HMAC-SHA-256 + SHA-256(ECDH x), exactly what the
        # fido2 0.8.1 client (and Windows webauthn) implements.
        self._assert_text('"cbc(aes)"', "AES-256-CBC primitive missing")
        self._assert_text('"hmac(sha256)"', "HMAC-SHA-256 primitive missing")
        self._assert_text('"ecdh-nist-p256"', "ECDH P-256 primitive missing")
        self._assert_text(
            "abk_fido_hmac_zero_iv", "zero-IV derivation constant missing"
        )

    def test_store_is_version_2_with_legacy_loader(self) -> None:
        self._assert_text(
            "#define ABK_FIDO_STORE_VERSION			2", "store version not 2"
        )
        self._assert_text(
            "abk_fido_store_from_disk_v1_into", "v1 store loader missing"
        )
        self._assert_text(
            "hmac_secret", "credential hmac_secret field missing"
        )

    def test_v1_loader_accepts_the_legacy_crc_form(self) -> None:
        # Blobs sealed by old driver variants use the plain crc32_le(0, ...)
        # form. Rejecting it would make the upgrade path reinitialize an
        # EMPTY store and wipe every credential, so both loaders must keep
        # accepting it.
        self._assert_text(
            "accepted legacy v1 store crc",
            "v1 loader lost the legacy-CRC fallback",
        )
        self._assert_text(
            "accepted legacy store crc",
            "v2 loader lost the legacy-CRC fallback",
        )

    def test_getinfo_advertises_the_extension(self) -> None:
        self._assert_text(
            'abk_cbor_put_text(&w, "hmac-secret");',
            "getInfo extensions list does not advertise hmac-secret",
        )

    def test_credential_without_secret_gets_invalid_option(self) -> None:
        self._assert_text(
            "has no secret", "missing-secret refusal trace missing"
        )
        self._assert_text(
            "return ABK_FIDO_ERR_INVALID_OPTION;",
            "missing-secret does not answer CTAP2_ERR_INVALID_OPTION",
        )

    def test_selftest_sysfs_node_is_registered(self) -> None:
        self._assert_text(
            "static struct kobj_attribute hmac_selftest_attr",
            "hmac_selftest attr missing",
        )
        self._assert_text(
            "&hmac_selftest_attr.attr,", "hmac_selftest not in attr group"
        )


if __name__ == "__main__":
    unittest.main()
